Hw01 calc cli
RomanVr/HW-2020-12-React pull request #1
Opened 2021-02-03 19:27 UTC by RomanVr

2021-02-03 21:07 UTC, AntiHero requested changes

2021-02-03 21:07 UTC, AntiHero commented on HW01-CalcCLI/src/greeting.ts
> +  return expression;
на этом работа программы заканчивается, было бы здорово,  если бы пользователь мог ещё вводить какие либо выражения для вычислений, и, например, при наборе в строке exit программа бы завершала работу

2021-02-03 21:17 UTC, AntiHero requested changes

2021-02-03 21:17 UTC, AntiHero commented on HW01-CalcCLI/src/data.ts
> +export const operands: Set<string> = new Set([
обычно для обозначения констант такого вида используют CAMEL_CASE

2021-02-07 16:55 UTC, RomanVr commented on HW01-CalcCLI/Makefile
> +start:
Файл с коммандами консоли bash, упрощает ввод комманд. Совсем не нужен?

2021-02-07 16:57 UTC, RomanVr commented on HW01-CalcCLI/src/checks.ts
> +  // console.log(`input symbols: ${wordsInExpression}`);
Да согласен, не дочистил. Debug не хотел тут использовать.

2021-02-07 16:59 UTC, RomanVr commented on HW01-CalcCLI/src/data.ts
> +  if (n === 0 || n === 1) {
Можно, ведь используем типизацию, немного наследия от js и не обращаешь внимание.

2021-02-07 17:01 UTC, RomanVr commented on HW01-CalcCLI/src/index.ts
> +    throw new Error("Our expression is not valid!");
Может сделать обработку в bin/executeRPN.ts? Была мысль так сделать, но ее не додумал.

2021-02-07 17:41 UTC, RomanVr commented on HW01-CalcCLI/src/greeting.ts
> +  return expression;
Ок, это не сложно.

2021-02-07 18:23 UTC, RomanVr commented on HW01-CalcCLI/src/data.ts
> +export const operands: Set<string> = new Set([
А как в этом случае быть со стрелочными функциями которые тоже присваиваются константе? Оставить как есть?

2021-02-09 12:14 UTC, AntiHero requested changes

2021-02-09 12:14 UTC, AntiHero commented on HW01-CalcCLI/Makefile
> +start:
спорно, но неплохо  его хотя  бы отформатировать

2021-02-09 12:14 UTC, AntiHero commented on HW01-CalcCLI/__tests__/index.test.ts
> +import execute from "../src";
это валидный путь? что и откуда импортируется?  проверьте  пожалуйста все  файлы  на  верный import/export

2021-02-09 12:14 UTC, AntiHero commented on HW01-CalcCLI/package.json
>      "startw": "webpack serve",
я бы  лучше назвал это start:dev

2021-02-09 12:14 UTC, AntiHero commented on HW01-CalcCLI/webpack.config.js
>      extensions: [".js", ".jsx", ".ts", ".tsx"],
вопрос, зачем нужен резолв и нужен ли?

2021-02-09 12:23 UTC, AntiHero commented on HW01-CalcCLI/src/data.ts
> +export const operands: Set<string> = new Set([
да, на стрелочные функции это не распростарняется

2021-02-09 12:24 UTC, AntiHero commented on HW01-CalcCLI/src/greeting.ts
> +  return expression;
а почему не использовать встроенный  "readline" ? https://nodejs.org/api/readline.html

2021-02-15 17:21 UTC, RomanVr commented on HW01-CalcCLI/Makefile
> +start:
Привел в консистентный вид, но что то прям не нашел гуглением прявил прямых для этого

2021-02-15 17:54 UTC, RomanVr commented on HW01-CalcCLI/src/greeting.ts
> +  return expression;
О! классно, надеюсь правильно использовал.

2021-02-15 17:58 UTC, RomanVr commented on HW01-CalcCLI/package.json
>      "startw": "webpack serve",
Да, так лучше.

2021-02-15 18:03 UTC, RomanVr commented on HW01-CalcCLI/__tests__/index.test.ts
> +import execute from "../src";
Ну если в паке лежит файл с именем index то его не указывают в пути import... 
Вроде все собиается...

2021-02-15 18:14 UTC, RomanVr commented on HW01-CalcCLI/Makefile
> +start:
Не нашел гуглением как правильно форматируется, но привел в консистентный вид, надеюсь правильно.

2021-02-15 18:21 UTC, RomanVr commented on HW01-CalcCLI/webpack.config.js
>      extensions: [".js", ".jsx", ".ts", ".tsx"],
Не не нужен, я alias не назначал, удалил...

2021-02-15 18:28 UTC, RomanVr commented on HW01-CalcCLI/webpack.config.js
>      extensions: [".js", ".jsx", ".ts", ".tsx"],
Хотя нет оставил, но такое ощущение, что webpack собирает bundle и без этого указания...

2021-02-15 19:27 UTC, AntiHero requested changes

2021-02-15 19:27 UTC, AntiHero commented on HW01-CalcCLI/package.json
> +    "startWebpack": "node out/bin/index.js",
а откуда bin взялся?

2021-02-15 19:27 UTC, AntiHero commented on HW01-CalcCLI/webpack.config.ts
> +    filename: "index.js",
ещё можно добавить  ` target: "node",` чтобы не было ошибки при сборке

> ERROR in ./src/bin/executeRPN.ts 1:0-32
> Module not found: Error: Can't resolve 'readline' in 'D:\OTUS\ДЗ\Воробьёв Роман\HW-2020-12-React\HW01-CalcCLI\src\bin'

2021-02-16 17:32 UTC, RomanVr commented on HW01-CalcCLI/package.json
> +    "startWebpack": "node out/bin/index.js",
Поправил, лишнее удалил

2021-02-16 17:32 UTC, RomanVr commented on HW01-CalcCLI/webpack.config.ts
> +    filename: "index.js",
Да немного разобрался, даже не догадывался, что так тоже можно :)

2021-02-16 18:42 UTC, AntiHero requested changes

2021-02-16 18:42 UTC, AntiHero commented on HW01-CalcCLI/src/bin/executeRPN.ts
> +const RL = readline.createInterface({
зачем с большой буквы? просто rl, в CAMEL_CASE называются константы-литералы

2021-09-03 11:53 UTC, closed without merging