Hw02 jsx base react.js
RomanVr/HW-2020-12-React pull request #2
Opened 2021-02-25 17:05 UTC by RomanVr

2021-02-28 13:44 UTC, AntiHero requested changes

2021-02-28 13:44 UTC, AntiHero commented on HW02-JSXbaseReactJS/src/components/field/field.tsx
> +interface Prop {
можно давать более уточняющие названия интерфейсам, чтобы в перспективе не возникало путаницы FieldProp, FieldState и т.д

2021-02-28 13:44 UTC, AntiHero commented on HW02-JSXbaseReactJS/src/components/field/field.tsx
> +}
storybook для Field и тест забыли сделать?

2021-02-28 13:44 UTC, AntiHero commented on HW02-JSXbaseReactJS/src/components/field/field.tsx
> +      size: props.start || 1,
а нужен ли здесь state, если это по стуи просто дублирование props?

2021-02-28 13:44 UTC, AntiHero commented on HW02-JSXbaseReactJS/src/components/field/field.tsx
> +          <Cell handleClick={this.handleClick} dataKey={i * 10 + j}>
чего-то не хватает https://reactjs.org/docs/lists-and-keys.html#keys

2021-02-28 13:44 UTC, AntiHero commented on HW02-JSXbaseReactJS/src/components/field/field.tsx
> +      field.push(<div style={{ display: "table-row" }}>{rowOfField}</div>);
и здесь https://reactjs.org/docs/lists-and-keys.html#keys

2021-02-28 13:44 UTC, AntiHero commented on HW02-JSXbaseReactJS/src/components/field/field.tsx
> +          <Cell handleClick={this.handleClick} dataKey={i * 10 + j}>
представим i = 1  j = 0, получим 10, а теперь i = 0, а j = 10, получим тоже 10, получается в двух разных рядах клетки с одинковым dataKey?

2021-02-28 13:51 UTC, AntiHero commented on HW02-JSXbaseReactJS/src/components/field/field.tsx
> +  handleClick(e: React.MouseEvent): void {
этот метод, как вариант, в том числе можно реализовать на уровне компонента Cell

2021-05-04 19:31 UTC, RomanVr commented on HW02-JSXbaseReactJS/src/components/field/field.tsx
> +}
Никак не могу сообразить от чего отталкиваться при написании сториев и тестов. Добавил, что сообразил, но кажется надо как то по другому.

2021-05-04 19:31 UTC, RomanVr commented on HW02-JSXbaseReactJS/src/components/field/field.tsx
> +      size: props.start || 1,
Да, поправил.

2021-05-04 19:31 UTC, RomanVr commented on HW02-JSXbaseReactJS/src/components/field/field.tsx
> +          <Cell handleClick={this.handleClick} dataKey={i * 10 + j}>
Угу, ключей добавил.

2021-05-04 19:31 UTC, RomanVr commented on HW02-JSXbaseReactJS/src/components/field/field.tsx
> +          <Cell handleClick={this.handleClick} dataKey={i * 10 + j}>
Что то не додумал...

2021-09-03 11:53 UTC, closed without merging