Hw03 type scrypt
RomanVr/HW-2020-12-React pull request #3
Opened 2021-05-08 12:18 UTC by RomanVr

2021-05-08 19:37 UTC, AntiHero requested changes

2021-05-08 19:37 UTC, AntiHero commented on HW03-TypeScript/package.json
> +    "@types/react": "^16.14.6",
это должно быть в devDependencies

2021-05-08 19:37 UTC, AntiHero commented on HW03-TypeScript/src/level1/easy1.ts
> +  const filteredStates = ([] as FIXME) as NewOrderState[];
зачем `as FIXME`?

2021-05-08 19:37 UTC, AntiHero commented on HW03-TypeScript/src/level1/easy2.ts
> +type OrderState = OrderOf["state"];
почему сразу не обратиться к свойству state Order?

2021-05-08 19:37 UTC, AntiHero commented on HW03-TypeScript/src/level2/medium2.ts
> +type getTypeDefaultProps<T> = T extends { defaultProps: unknown }
можно по другому с использованием типов, предоставляемых react и с использованием infer, как написано в подсказке
`type getTypeDefaultProps<T> = T extends React.ComponentType<infer U> ? React.ComponentType<U>["defaultProps"] : never`

2021-05-08 19:37 UTC, AntiHero commented on HW03-TypeScript/src/level2/medium3.ts
> +    (state) => state !== "buyingSupplies" && state !== "producing"
вот здесь и нужен type guard https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates, но чтобы его использовать нужно вначале "отфильтровать" наш исходный тип, на данный момент, он ожидает в качестве возвращаемого типа `OrderState[]`, но когда мы его отфильтруем, т.е. исключим из него с помощью некого utility type  `buyingSupplies` и ` producing`, тогда нам надо будет уточнить тип параметра state с помощью type guard, чтобы TS знал какой тип на выходе мы на самом деле хотим

2021-05-16 11:54 UTC, RomanVr commented on HW03-TypeScript/src/level1/easy1.ts
> +  const filteredStates = ([] as FIXME) as NewOrderState[];
Была не понятна конструкция выражения, делал как предлагает линтер. Вроде разобрался.

2021-05-16 11:54 UTC, RomanVr commented on HW03-TypeScript/package.json
> +    "@types/react": "^16.14.6",
Поправил

2021-05-16 12:04 UTC, RomanVr commented on HW03-TypeScript/src/level1/easy2.ts
> +type OrderState = OrderOf["state"];
Поправил

2021-05-16 18:43 UTC, RomanVr commented on HW03-TypeScript/src/level2/medium2.ts
> +type getTypeDefaultProps<T> = T extends { defaultProps: unknown }
Поправил

2021-05-16 19:13 UTC, RomanVr commented on HW03-TypeScript/src/level2/medium3.ts
> +    (state) => state !== "buyingSupplies" && state !== "producing"
Вроде разобрался, поправил.

2021-09-03 11:53 UTC, closed without merging